### ISSUE TITLE
So Much Problems with Arduino UNO

### ISSUE THREAD

**Issue by zhangysh1995** [Seeed-Studio/Grove_LCD_RGB_Backlight#8]
I got a lot of bugs when compiling the example code "HelloWorld".

Actually it seems the original code is such a mess.  Bugs says "Undefined reference to xxx", I couldn't deal with it even after looked at the header file code.

If it is my fault, I will cancel this issue.

**Comment by ReanimationXP** [comment]
This code is probably outdated since some libraries like Wire.h are now included in Arduino by default.

I navigated to my local copy of
https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/master/rgb_lcd.cpp
and commented out `//#include <Wire.h>`

Secondly I navigated to my local copy of
https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/master/rgb_lcd.h
and commented out `//#include "Print.h"`

Finally I did the same on the example code,
https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/master/examples/HelloWorld/HelloWorld.ino
commenting out `//#include <Wire.h>`

This fixed up the Hello World example for me.

**Comment by jsilence** [comment]
The text is displayed when setting the display to one row:
`lcd.begin(16, 1);`
But then really only one row is usable. And the contrast of the text is very low.
Opening a separate issue for this.

**Comment by awong1900** [comment]
I can't found that compiling issue, so close. And feel free to fix it and I'll merge the change.
